### PR TITLE
Circuit drawer fix

### PR DESCRIPTION
**Pull request by nquesada**
**Context:**
Adds a minor tweak in the circuit drawer so that the pdfs generated do not have page numbering. That way they are easier to crop.

**Description of the Change:**
Adds two lines to circuit drawer.
**Benefits:**
The pdf generated from circuit drawer can be easily cropped  with eg pdfcrop.

### CODE REVIEW

**Comment by josh146** [comment]
Looks good to be merged in when the tests pass, thanks @nquesada

**Comment by josh146** [comment]
@nquesada, looks like the tests will also need to be updated to take into account this change!

**Comment by co9olguy** [comment]
I think line 47 [here](https://github.com/XanaduAI/strawberryfields/blob/master/tests/frontend/test_circuitdrawer.py) will have to be updated

**Comment by nquesada** [comment]
It never crossed my mind that there were tests for this... Anyway they pass in my local machine and should hopefully pass on travis...

**Pull request merged**
