### PR TITLE
Test a possible bug in the backend.

### PR DESCRIPTION
**Pull request by nquesada**

### CODE REVIEW

**Review by elib20 — APPROVED** [review]

**Comment by josh146** [comment]
@nquesada what bug does this fix? It would be good to include a test for it, just for (a) verification is fixes it, and (b) making sure we catch this bug in the future.

Also don't forget to update the changelog!

**Comment by co9olguy** [comment]
How come this bug needed to be tested via PR? :thinking:

**Comment by nquesada** [comment]
@co9olguy so that all the tests are run?

**Comment by co9olguy** [comment]
How come you didn't want to run the tests locally?

**Pull request closed without merging**
