### PR TITLE
Avoid `VisibleDeprecationWarning` by specifying `dtype` for `ndarray`

### PR DESCRIPTION
**Pull request by antalszava**
Newer numpy version (e.g., `numpy==1.20.2`) raise a warning for constructing ragged arrays:
```
strawberryfields/backends/states.py:1633: VisibleDeprecationWarning:
Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
```
This PR applies the suggestion from the warning message at two places.

### CODE REVIEW

**Review by josh146 — COMMENTED** [review]
Thanks @antalszava for finding and catching this!

I have a question though - is the created array _always_ ragged? I think it is only ragged if the user-provided `xvec` and `pvec` are different lengths.

In which case, we should branch depending on this condition. That way, a standard NumPy array is still created if X and P are the same length.

**Comment by antalszava** [comment]
@josh146 had a closer look at this, a ragged array is created even if the user provided vectors have the same length:
```python
import numpy as np
import strawberryfields as sf

nmodes = 2
epsilon = 0.1
sf.hbar = 1
prog_linear_cluster = sf.Program(nmodes)

with prog_linear_cluster.context as q:
    sf.ops.GKP(state=[0.5*np.pi, 0], epsilon=epsilon) | q[0]
    sf.ops.Squeezed(r = -5) | q[1]

eng = sf.Engine("bosonic")
result = eng.run(prog_linear_cluster)
vec = np.linspace(-5, 5, num=200)
sf.plot.plot_wigner(result.state, 0, vec, vec)
```
Here we use `vec` twice, and the warning still arises. The reason is, that under the hood we use `X, P = np.meshgrid(xvec, pvec, sparse=True)`, where having `sparse=True` will change the shape of `X` and `P`.

```python
vec = np.linspace(-5, 5, num=200)
mesh = np.meshgrid(vec, vec, sparse=True)
print(mesh[0].shape, mesh[1].shape)

mesh = np.meshgrid(vec, vec)
print(mesh[0].shape, mesh[1].shape)
```
```
(1, 200) (200, 1)
(200, 200) (200, 200)
```
Added a condition nonetheless. :slightly_smiling_face:

**Review by josh146 — APPROVED** [review]
Ah, thanks for solving this @antalszava! I didn't realize about the `sparse` argument 🙂

**Comment by josh146** [comment]
P.S., don't forget to update the changelog!

**Pull request merged**
