### PR TITLE
Rewrite XQC API version to 0.2.0 and add User-Agent

### PR DESCRIPTION
**Pull request by jswinarton**
**Context:**
The current version of StrawberryFields sends an incorrect version header to the Xanadu Quantum Cloud API.

**Description of the Change:**
- Update the `Accept-Version` header of requests sent from the `strawberryfields.api.connection` module to `0.2.0` instead of `1.0.0`
- Add a custom User-Agent string which sends a header in the standard format `StrawberryFields/0.17.0` where `0.17.0` is the current version of StrawberryFields

**Benefits:**
- Allows compability with the XQC platform in future iterations where API versioning will be more strict
- The `User-Agent` string gives important contextual information to the XQC API which can be used to provide custom behaviour in the future (for example, rewriting behaviour in the case of problematic requests, or providing deprecation notices in the event of lifecycle changes in the API)

**Possible Drawbacks:**
N/A

**Related GitHub Issues:**
N/A

### CODE REVIEW

**Review by corvust — APPROVED** [review]

**Review by antalszava — APPROVED** [review]
Looks good to me, thank you! :100:

In the future, we'd like to change the API version sent by Strawberry Fields when there's a new API version of XQC that we would like to start using, correct? Would that potentially influence release cycles?

**Review by thisac — APPROVED** [review]
Looks good as far as I can tell. :+1: As @antalszava mentioned, I assume this is something that we'll need to update each time we want to start using a new version of the api.

**Comment by jswinarton** [comment]
@antalszava @thisac Yeah, that's the idea. Depending on the speed of work on our end they may be frequent, but how you decide to release these on your end is up to you. For example we'll have version 0.3.0 coming out soon with our new device API, which will give you access to dynamic device information, but maybe you don't have time to integrate that on your side for a while. That's fine because we'll continue to support old versions for a period.

**Review by josh146 — APPROVED** [review]

**Comment by josh146** [comment]
@jswinarton before you merge this in, can you update the changelog? Thanks!

**Pull request merged**
