### PR TITLE
Latex Circuit Drawer

### PR DESCRIPTION
**Pull request by MackEdweise**
**Description of the Change:**

This change includes a tested circuit drawer module that is able to create latex code for the visualization of circuits that represent the applied or queued operations in a quantum circuit within the context of a Strawberryfields engine.

The module is also capable of compiling a quantum circuit to a pdf given that the execution environment has an installation of latex available.

The change includes a new engine method `draw_circuit(self, print_queued_ops=True)` which makes use of the previously defined `print_applied(self, print_fn=print)` and `print_queue(self, print_fn=print)` methods to expose the circuit drawer module to Strawberryfields users.

The module is able to generate latex for quantum circuits containing the following gates:

single-mode gates
-----------------
Dgate
Xgate
Zgate
Sgate
Rgate
Pgate
Vgate
Kgate
Fouriergate

Two-mode gates
--------------
BSgate
S2gate
CXgate
CZgate
CKgate

Each gate is tested being applied to at least two different subsystems. Additional cases that are tested fir most gates include the application of multiple gates in sucession to different subsystems in a circuit, and the repeated application of a single gate to the same subsystem. 

**Benefits:**

Circuits that are programmatically created in Strawberryfields can be visualized easly so that they can be used in reports, papers, etc.

**Possible Drawbacks:**

Users must configure and make user of a latex compilation tool on their own to make pdfs.

**Related GitHub Issues:**

### CODE REVIEW

**Comment by josh146** [comment]
Hi @MackEdweise, thank you for this high quality pull request! The feature set looks great.

I've only had a quick look through the Travis CI build, and the reason the Python 3.5 build is failing is due to the use of f-strings (which are only supported on Python 3.6 and above). So it should be easy to convert these into standard format strings.

I'll go through and do a code review today 🙂

**Comment by MackEdweise** [comment]
Looks like I will need to add a few mnore unit tests.

**Comment by MackEdweise** [comment]
And that is exactly what tests are for... writing those to get the code coverage up helped me notice a bug and a mistake.

**Comment by josh146** [comment]
Looks like the f-strings were the only issue, all tests now passing 🙂

**Comment by MackEdweise** [comment]
Hm I see that we want docstrings on every method... apologies, I will have to add a few of those.

**Comment by josh146** [comment]
Hi @MackEdweise, I've cloned and starting going through your PR. Very exciting, been looking forward to having a circuit drawer in Strawberry Fields for a while!

I've just made a small commmit to the PR, integrating the docstrings in `circuitdrawer.py` with the documentation. If you run `make docs`, and then open `doc/_build/html/index.html`, you will then find `Circuit drawer` in the sidebar. This will be useful as you add the docstrings, making sure that everything renders correctly. Have a look through the rest of the API documentation (particularly `engine.py`), and conform to the Strawberry Fields documentation style where needed 🙂 

With regards to the circuit drawer itself, the plain text LaTeX output works great! Unfortunately, I couldn't get the compilation (with `compile_pdf=True`) to work on my end:

1. The `subprocess` first returns an error, as the `circuit_pdfs` and `circuit_tex` directories do not exist.

2. After creating these directories manually, the subprocess command continues to error, with the following output:

   ```python
   FileNotFoundError: [Errno 2] No such file or directory:
   'pdflatex -output-directory circuit_pdfs circuit_tex/output_2019_January_13_07:25PM.tex'
   ```

   I got stuck at this point, as as far as I can tell, the tex file above does exist at that location.

A good idea would be to check if the directories exist, and if not, create them automatically in Python. Even better, you could make use of [`tempfile` standard library](https://docs.python.org/3/library/tempfile.html), which provides automatic cleanup and convenient context managers.

As you continue to work on the PR, I suggest editing the title to prepend it with '[WIP]' (work in progress). Let me know how you go, and feel free to continue posting any status updates here.

**Comment by josh146** [comment]
Hi @MackEdweise, I've had a quick skim through the PR changes, and everything is looking really great! Everything is well documented, docstrings are informative, and the tests look great. Are you ready for a code-review, or are you still working on it?

**Comment by MackEdweise** [comment]
The only issue I'm aware of is the test coverage but I am struggling a bit to identify more meaningful tests to write. Otherwise yes, the PR is ready for a review :)

**Comment by josh146** [comment]
Perfect, I can do a code review now (and perhaps also help identify/write any extra tests)

**Comment by MackEdweise** [comment]
Awesome, thank you!

**Comment by josh146** [comment]
I've just pushed a small commit that fixes some formatting issues in the documentation (if you want to check it out for yourself, run `make docs` in the terminal, and then go through the table of contents for the 'Circuit drawer' option :slightly_smiling_face:)

I can't quite seem to compile a small example that uses `draw_circuit()` on the engine, I get the following error:
```bash
Runaway argument?
{ & \gate {D} & \qw [1] & \gate {BS} \\ & \gate {S} & \gate {BS} & \gate \ETC.
! Paragraph ended before \next@ was complete.
<to be read again> 
                   \par 
l.7 
    
? 
```

**Comment by MackEdweise** [comment]
> I've just pushed a small commit that fixes some formatting issues in the documentation (if you want to check it out for yourself, run `make docs` in the terminal, and then go through the table of contents for the 'Circuit drawer' option 🙂)
> 
> I can't quite seem to compile a small example that uses `draw_circuit()` on the engine, I get the following error:
> 
> ```shell
> Runaway argument?
> { & \gate {D} & \qw [1] & \gate {BS} \\ & \gate {S} & \gate {BS} & \gate \ETC.
> ! Paragraph ended before \next@ was complete.
> <to be read again> 
>                    \par 
> l.7 
>     
> ? 
> ```

Odd, any chance you could share the small example and any output files?

**Comment by josh146** [comment]
Sure, this is what I tried:

```python
import strawberryfields as sf
from strawberryfields.ops import *
from numpy import pi

eng, q = sf.Engine(3)

with eng:
    # prepare initial states
    Dgate(1+0.5j) | q[0]
    Sgate(-2) | q[1]
    Sgate(2) | q[2]

    # apply gates
    BS = BSgate(pi/4, pi)
    BS | (q[1], q[2])
    BS | (q[0], q[1])

eng.draw_circuit()
```

which gives the output
```python
['/home/josh/strawberryfields/circuit_tex/output_2019_February_15_11:38AM.tex',
 '\\documentclass{article}\n\\usepackage{qcircuit}\n\\Qcircuit {\n & \\gate{D}  & \\qw[1]  & \\gate{BS} \\\\\n & \\gate{S}  & \\gate{BS}  & \\gate{BS} \\\\\n & \\gate{S}  & \\gate{BS}  & \\qw[1] \\\\\n\n}\n\\end{document}']
```

**Comment by MackEdweise** [comment]
> Sure, this is what I tried:
> 
> ```python
> import strawberryfields as sf
> from strawberryfields.ops import *
> from numpy import pi
> 
> eng, q = sf.Engine(3)
> 
> with eng:
>     # prepare initial states
>     Dgate(1+0.5j) | q[0]
>     Sgate(-2) | q[1]
>     Sgate(2) | q[2]
> 
>     # apply gates
>     BS = BSgate(pi/4, pi)
>     BS | (q[1], q[2])
>     BS | (q[0], q[1])
> 
> eng.draw_circuit()
> ```
> 
> which gives the output
> 
> ```python
> ['/home/josh/strawberryfields/circuit_tex/output_2019_February_15_11:38AM.tex',
>  '\\documentclass{article}\n\\usepackage{qcircuit}\n\\Qcircuit {\n & \\gate{D}  & \\qw[1]  & \\gate{BS} \\\\\n & \\gate{S}  & \\gate{BS}  & \\gate{BS} \\\\\n & \\gate{S}  & \\gate{BS}  & \\qw[1] \\\\\n\n}\n\\end{document}']
> ```

Hi Josh, thanks a lot for that context! I was able to reproduce the issue by trying to compile the circuit in an environment without `qcircuit.sty` installed. I was able to compile to document to `.pdf` in an environment with `qcircuit.sty`. Please check if that is also what is happening on your end. `qcircuit.sty` can be found at http://mirror.las.iastate.edu/tex-archive/graphics/qcircuit/qcircuit.sty .

**Comment by josh146** [comment]
Ah, of course - I've been using a workflow where I simply include `qcircuit.sty` in the same directory, but for some reason that doesn't work here. Installing `qcircuit.sty` properly does the trick!

**Comment by MackEdweise** [comment]
I have added the `\begin{document}` command to the top of each circuit. I was able to compile output circuits without it before so didn't notice it was missing, but of course realize that it should be there and that the output needs to be well-formed.

**Comment by trbromley** [comment]
Hi @MackEdweise, looks like a really useful addition to Strawberry Fields!

I had a go at running the example code shared by @josh146 and had some trouble compiling the output latex file (code shown below) using both Texmaker and pdflatex in the terminal.

```
\documentclass{article}
\usepackage{qcircuit}
\begin{document}
\Qcircuit {
 & \gate{D}  & \qw[1]  & \gate{BS} \\
 & \gate{S}  & \gate{BS}  & \gate{BS} \\
 & \gate{S}  & \gate{BS}  & \qw[1] \\

}
\end{document}
```

I had to remove the extra line on line 8 to get things to work with pdflatex, and also the '[1]' in '\qw[1]' instances for Texmaker to compile. It looks like these two features occur when outputting latex code for any circuit, and not just for the example above. The output circuit looks like this:
Circuit
This requires a couple of tweaks before matching the objective circuit:
- beamsplitters should be a single box connecting the interacting modes
- circuits should end with an additional quantum wire, which can be fixed by adding a final column of '\qw' to the qcircuit code.

Here is what the output circuit should look like:
Circuit2
with latex code:

```
\documentclass{article}
\usepackage{qcircuit}
\begin{document}
\Qcircuit {
 & \gate{D}  & \qw  & \multigate{1}{BS} & \qw \\
 & \gate{S}  & \multigate{1}{BS}  & \ghost{BS} & \qw \\
 & \gate{S}  & \ghost{BS}  & \qw & \qw \\
}
\end{document}
```

Thanks for working on this circuit drawer, really excited to use it!
Cheers,
Tom

**Comment by MackEdweise** [comment]
> Hi @MackEdweise, looks like a really useful addition to Strawberry Fields!
> 
> I had a go at running the example code shared by @josh146 and had some trouble compiling the output latex file (code shown below) using both Texmaker and pdflatex in the terminal.
> 
> ```
> \documentclass{article}
> \usepackage{qcircuit}
> \begin{document}
> \Qcircuit {
>  & \gate{D}  & \qw[1]  & \gate{BS} \\
>  & \gate{S}  & \gate{BS}  & \gate{BS} \\
>  & \gate{S}  & \gate{BS}  & \qw[1] \\
> 
> }
> \end{document}
> ```
> I had to remove the extra line on line 8 to get things to work with pdflatex, and also the '[1]' in '\qw[1]' instances for Texmaker to compile. It looks like these two features occur when outputting latex code for any circuit, and not just for the example above. The output circuit looks like this:
> Circuit
> This requires a couple of tweaks before matching the objective circuit:
> 
> * beamsplitters should be a single box connecting the interacting modes
> * circuits should end with an additional quantum wire, which can be fixed by adding a final column of '\qw' to the qcircuit code.
> 
> Here is what the output circuit should look like:
> Circuit2
> with latex code:
> 
> ```
> \documentclass{article}
> \usepackage{qcircuit}
> \begin{document}
> \Qcircuit {
>  & \gate{D}  & \qw  & \multigate{1}{BS} & \qw \\
>  & \gate{S}  & \multigate{1}{BS}  & \ghost{BS} & \qw \\
>  & \gate{S}  & \ghost{BS}  & \qw & \qw \\
> }
> \end{document}
> ```
> Thanks for working on this circuit drawer, really excited to use it!
> Cheers,
> Tom

Thank you, Tom! This is fantastic feedback. I have made a commit attempting to address each of these issues. Let me know how it looks. :)

**Comment by trbromley** [comment]
Hey @MackEdweise, these look like great changes!

I just noticed a few more tweaks that are needed:
- I can't get the `Fouriergate` to work in a circuit, due to the error: `strawberryfields.circuitdrawer.UnsupportedGateException: Unsupported operation Fourier | (q[2]) not printable by circuit builder!`
- The drawn circuit should have longer quantum wires at the output. Currently it looks like:
before
but it should look like:
after
It looks like you already tried to address this but I can't get it to work.
- Finally, we should be careful with the situation where a user connects a beamsplitter between non-neighbouring modes (e.g. mode 0 and 2). Currently, the circuit drawer outputs the following for when the last beamsplitter is set between mode 0 and 2:
Beamsplitter
which is not quite right. Moreover, it's not clear how a circuit drawer _should_ draw this, as the interaction would need to cross the line of mode 1 but be clear that it's not interacting with that mode. The qcircuit package suggests using the `\sgate` command for this situation. However, it may be simpler in the circuit drawer to just raise an exception when beamsplitters and any other two-mode gates apply to non-neighbouring modes.

Other than that, for me this looks like a great pull request!
Thanks
Tom

**Comment by MackEdweise** [comment]
> Hey @MackEdweise, these look like great changes!
> 
> I just noticed a few more tweaks that are needed:
> 
> * I can't get the `Fouriergate` to work in a circuit, due to the error: `strawberryfields.circuitdrawer.UnsupportedGateException: Unsupported operation Fourier | (q[2]) not printable by circuit builder!`
> * The drawn circuit should have longer quantum wires at the output. Currently it looks like:
>   before
>   but it should look like:
>   after
>   It looks like you already tried to address this but I can't get it to work.
> * Finally, we should be careful with the situation where a user connects a beamsplitter between non-neighbouring modes (e.g. mode 0 and 2). Currently, the circuit drawer outputs the following for when the last beamsplitter is set between mode 0 and 2:
>   Beamsplitter
>   which is not quite right. Moreover, it's not clear how a circuit drawer _should_ draw this, as the interaction would need to cross the line of mode 1 but be clear that it's not interacting with that mode. The qcircuit package suggests using the `\sgate` command for this situation. However, it may be simpler in the circuit drawer to just raise an exception when beamsplitters and any other two-mode gates apply to non-neighbouring modes.
> 
> Other than that, for me this looks like a great pull request!
> Thanks
> Tom

Thanks so much for your attention on this PR, Tom. I have made another commit attempting to address these three remaining issues.

**Comment by trbromley** [comment]
Thanks to you for the prompt changes!

For the multimode gates, note that the wires fed in by the user are not necessarily ordered, for example a user can enact a beamsplitter on modes 0 and 1 with `BS | (q[1], q[0])`. Currently this raises a `NotDrawableException` in the circuit drawer, but this should be an easy fix by imposing an preordering on the wires.

Cheers
Tom

**Comment by MackEdweise** [comment]
> Thanks to you for the prompt changes!
> 
> For the multimode gates, note that the wires fed in by the user are not necessarily ordered, for example a user can enact a beamsplitter on modes 0 and 1 with `BS | (q[1], q[0])`. Currently this raises a `NotDrawableException` in the circuit drawer, but this should be an easy fix by imposing an preordering on the wires.
> 
> Cheers
> Tom

Thanks for catching that. Looks like I needed to move the sort up a few lines to take into account the first index being out of order. Hopefully that is now fixed!

**Comment by trbromley** [comment]
Hi @MackEdweise, looks great to me! Thanks!

**Comment by MackEdweise** [comment]
Awesome, do you have any more feedback before this is merge-worthy? :)

**Comment by josh146** [comment]
Hi @MackEdweise, it's looking fantastic now, and from an implementation point-of-view definitely ready for a merge (thanks @trbromley for your feedback!).

The last thing I'll need to get you to do before merging is add to the tests to ensure decent test coverage of the circuit drawer. Currently, it looks like the engine draw circuit method isn't being tested directly, and only 26% of `circuitdrawer.py` is being tested.

**Comment by MackEdweise** [comment]
> Hi Marcus, it's looking fantastic now, and from an implementation point-of-view definitely ready for a merge (thanks @trbromley for your feedback, and @MackEdweise for your quick responses and fixes!)
> 
> The last thing I'll need to get you to do before merging is add to the tests to ensure decent test coverage of the circuit drawer. Currently, it looks like the engine draw circuit method isn't being tested directly, and only 26% of `circuitdrawer.py` is being tested.

Hi Josh, thanks for the feedback. 

I am finding it difficult to understand how this number 26% could be accurate. I have had a passing code coverage for over a month, and have not added any additional code paths or removed any tests since. Rather, I have only added tests. For example:
Screen Shot 2019-04-16 at 5 09 45 PM

Has something changed about how the coverage is calculated? I am quite sure I have tested about every method in `circuitdrawer.py`. I will try to dig into this a bit more.

**Comment by josh146** [comment]
Oh, thanks for noting that, that is odd. I'll run the test suite locally and double check.

**Comment by MackEdweise** [comment]
> Oh, thanks for noting that, that is odd. I'll run the test suite locally and double check.

Thanks, I appreciate your investigation :)

**Comment by josh146** [comment]
After running it locally, the issue must be a combination of Codecov/our process of porting the test suite to pytest. Sorry about that! Test coverage is looking fantastic, with only 3 lines missing.

It would be great if you could add three quick tests to check for the following:

*  `raise UnsupportedGateException` is raised in the correct circumstance (line 197 of `circuitdrawer.py`)

* `raise ModeMismatchException` is raised in the correct circumstance (line 201 of `circuitdrawer.py`)

* `draw_circuit` with `print_queued=False` correctly calls `self.print_applied(circuit.parse_op)` (line 724 of `engine.py`). This should be a quick one, a matter of just copying an existing test with a small modification.

Once that's done, merging will begin (and message me for your Xanadu swag!)

**Comment by MackEdweise** [comment]
> After running it locally, the issue must be a combination of Codecov/our process of porting the test suite to pytest. Sorry about that! Test coverage is looking fantastic, with only 3 lines missing.
> 
> It would be great if you could add three quick tests to check for the following:
> 
> * `raise UnsupportedGateException` is raised in the correct circumstance (line 197 of `circuitdrawer.py`)
> * `raise ModeMismatchException` is raised in the correct circumstance (line 201 of `circuitdrawer.py`)
> * `draw_circuit` with `print_queued=False` correctly calls `self.print_applied(circuit.parse_op)` (line 724 of `engine.py`). This should be a quick one, a matter of just copying an existing test with a small modification.
> 
> Once that's done, merging will begin (and message me for your Xanadu swag!)

Woohoo! Thanks so much for looking into that. Excited to ship this module. I will add these last tests soon! :)

**Comment by MackEdweise** [comment]
> After running it locally, the issue must be a combination of Codecov/our process of porting the test suite to pytest. Sorry about that! Test coverage is looking fantastic, with only 3 lines missing.
> 
> It would be great if you could add three quick tests to check for the following:
> 
> * `raise UnsupportedGateException` is raised in the correct circumstance (line 197 of `circuitdrawer.py`)
> * `raise ModeMismatchException` is raised in the correct circumstance (line 201 of `circuitdrawer.py`)
> * `draw_circuit` with `print_queued=False` correctly calls `self.print_applied(circuit.parse_op)` (line 724 of `engine.py`). This should be a quick one, a matter of just copying an existing test with a small modification.
> 
> Once that's done, merging will begin (and message me for your Xanadu swag!)

I've added these last tests. Let me know what you think. :)

**Comment by josh146** [comment]
Looks great @MackEdweise. Due to master having ported the tests to pytest while you were working on this PR, I'm going to merge in the latest upstream, and move the tests you have written into the new `pytest` folder.

**Pull request merged**
