### PR TITLE
New state preps multimode

### PR DESCRIPTION
**Pull request by cgogolin**
**Description of the Change:**
This fully implements the single and multi mode state preparations in the fock and tf backends as specified in #16 and adds various corresponding unit tests tests. The implementation is a little bit more general than would have been necessary, as it allows the target mode list to be out of order and then correctly reorders the modes.
**TODO**
- The multimode functions are not yet included in the base.py
- The API needs some thought. It might make sense to remove the single mode versions of the state preparation methods (wich already now simply call through to the multi mode variants) and rename the multimode variants
**Benefits:**
- Allows the preparation of arbitrary single and multi mode states or arbitrary modes 
- The order of the specified modes is taken into account when interpreting the input
- The state() methods that returns the state can now also return correctly reordered states of a list of modes that needs not be sorted.
**Possible Drawbacks:**
- The newly implemented code does not always use the `tensor()`, `insert()`, and similar methods in the corresponding ops.py files, but rather calls numpy/tensor flow directly, as these were written in a way that was hard to generalize.  
**Related GitHub Issues:**
#16

### CODE REVIEW

**Comment by cgogolin** [comment]
The last few commits implement the API changes we discussed earlier. This resolves the two open TODO points mentioned in the initial pull request.

**Comment by cgogolin** [comment]
If all tests pass, I will, as a final step, run local test with `tensorflow==1.3` and then give green light for merging if all goes well.

**Comment by cgogolin** [comment]
Turns out that the way I am now using `tf.tensordot()` in `/tfbackend/ops.py` in line 744, in replace_modes, namely:
```revised_modes = tf.tensordot(reduced_state, replacement, axes=0)```
raises a
```ValueError: 'axes' must be at least 1.```
with `tensorflow<=1.4`. From `1.5` onwards all works.

Would a dependency on `tensorflow>=1.5` be acceptable, or shall I look for a workaround? Alternatively one can probably add a fake dimension and then `tensordot` that away conditional on `tensorflow<=1.4`.

**Comment by co9olguy** [comment]
Hmm... It would definitely be preferable to find a workaround that doesn't require checking which version of Tensorflow is installed

**Comment by cgogolin** [comment]
As python packages have no numerical version numbers, comparing version is indeed a not a good idea (tough there are solutions: https://stackoverflow.com/questions/20180543/how-to-check-version-of-python-modules). 

It turns out that one can indeed replace
```            revised_modes = tf.tensordot(reduced_state, replacement, axes=0)```
by
```            revised_modes = tf.tensordot(tf.expand_dims(reduced_state, 0), tf.expand_dims(replacement, 0), axes=[[0],[0]])```
and the latter works with `tensorflow>=1.3`.

I am sure this hack of adding extra dimensions it not exactly efficient, so I put a todo so that we can remember to remove it once `tensorflow>=1.6` becomes a dependency.

**Pull request merged**
